development:
  adapter: postgresql
  encoding: unicode
  database: friday-development
  pool: 5
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: friday-test
  pool: 5
  port: 5432